### ISSUE TITLE
CSS rendering Issue

### ISSUE THREAD

**Issue by rajreeshu** [rajreeshu/modularFrontend#2]
```CSS
.emoji-container:hover .static-emoji {
       opacity: 0;
}
```

This CSS is not rendered correctly

It should Create 
```css
.emoji-container_abc:hover .static-emoji_abc {
       opacity: 0;
}
```
But insted it is creating 
```css
.hello_abc:hover .world_abc { 
     color: red; 
}
```
