### ISSUE TITLE
CSS rendering Issue

### ISSUE THREAD

**Issue by rajreeshu** [rajreeshu/modularFrontend#3]
```html
<div class="hello_abc">
    <div class="world_abc">Hello</div>
</div>
```
```CSS
.hello .world::before {
  content: "Progress: ";
  color: green;
}
```
This CSS should create 
```Css
.hello_abc .world_abc::before {
  content: "Progress: ";
  color: green;
}
```
Instead it is rendering to 
```CSS
.hello .world::before { 
     content: "Progress: "; color: green; 
}
```
